version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data://c/Users/chema/workspaces/oxy-workspace/banking-challenge/data
volumes:
  database-data: